# Generated by Django 5.2.8 on 2025-11-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('propietario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField(max_length=200)),
                ('categoria', models.CharField(choices=[('rapida', 'Comida rápida'), ('mexicana', 'Comida mexicana'), ('italiana', 'Comida italiana'), ('asiatica', 'Comida asiática'), ('vegetariana', 'Comida vegetariana')], max_length=20)),
                ('horario_apertura', models.TimeField()),
                ('horario_cierre', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
